### ISSUE TITLE
Privacy & Security / Bluetooth

### ISSUE THREAD

**Issue by Kyome22** [piarasj/piarasj.github.io#2]
Privacy & Security / Bluetooth screen is at

```
x-apple.systempreferences:com.apple.preference.security?Privacy_Bluetooth
```

I recommend adding the above path to [ventura_settings.md](https://github.com/piarasj/piarasj.github.io/blob/master/ventura_settings.md).

**Comment by piarasj** [comment]
Done - thanks!
